# Only used for dev atm!
version: "3"
services:
  ## Running in Docker slows down development a lot, so this is only kept for reference here.
  # nextjs:
  #   image: "node:22"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "./:/usr/src/app:delegated"
  #   working_dir: "/usr/src/app"
  #   command: ["sh", "-c", "yarn && yarn dev"]
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: "postgres://postgres:password@db:5432/template1"
  #   restart: "always"
  db:
    image: "postgres:16"
    ports:
      - "5433:5432"
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_DB: "visualization_tool"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
